---
version: 2
updates:
  # Keep Docker base images up to date
  - package-ecosystem: "docker"
    directory: "/docker/debian"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "daily"
      time: "12:30"
    reviewers:
      - "btlogy"
  # Keep Github Actions up to date
  # Bump the dependencies of the re-usable actions published here
  - package-ecosystem: "github-actions"
    directory: "/actions"
    schedule:
      interval: "daily"
      time: "12:30"
    reviewers:
      - "btlogy"
  # Bump the dependencies consumed by the CI workflow running here
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "12:30"
    reviewers:
      - "btlogy"
